auth0/auth0-drupal

- auth0.install
- auth0.module
The module needs a little minor style cleanup to be contributed on drupal.org.
See: https://www.drupal.org/coding-standards
> Drupal cleanup

- auth0.module
I added a bug which was sending a non-absolute url as for redirecting after SSO logout
> Fix redirect on logout

- auth0.install
- auth0.module
This PR fixes a few places where Drupal coding standards are not followed. This resolves all warnings identified by Coder Review module.
Hope this can help with the project application process.
> Code style updates

- composer.json
This addresses the blocker for #35.
> Rename package name to work with Drupal 8

- composer.json
> Revert "Rename package name to work with Drupal 8"

- src/Controller/AuthController.php
> Remove autoloader include

- auth0.module
- composer.json
- composer.lock
This enhancement adds the ability to map Auth0 claims to Drupal user profile fields as well as the ability to select a claim to be used to map to a set of granted roles for the user.
> Add ability to map claims to user profile fields and to roles

- composer.json
This addresses the blocker for #35
> Rename package to work with composer installer

- src/Event/Auth0UserSigninEvent.php
- src/Event/Auth0UserSignupEvent.php
Makes development friendlier and more intuitive in IDEs like PHPStorm. Class/method completion, etc.
> Add type hinting to sign-up/sign-in events

- README.txt
- auth0.module
- composer.json
- composer.lock
Add RS256 support
Add non-base64 encoded secret support
@glena I'm wondering if we should create a new branch called d7-2.x.x instead of pushing this to 1.x.x
> Add prompt=none redirect support for SSO

- README.txt
- auth0.module
- composer.json
- composer.lock
> Revert "Add prompt=none redirect support for SSO"

- README.txt
- auth0.module
- composer.json
- composer.lock
Add RS256 support
Add non-base64 encoded secret support
> Use prompt=none to support OIDC Conformant

- README.txt
- auth0.install
- auth0.routing.yml
- composer.json
- src/Controller/AuthController.php
- src/Form/BasicAdvancedForm.php
- src/Form/BasicSettingsForm.php
- templates/auth0-login.html.twig
1) Added support to be able to turn on the OIDC Conformance flag
2) Validating the id_token when it comes back now
3) Support RS256 for the ID token
4) With redirect on login, need to override the redirect on logout
5) With OIDC conformance need to be able to fetch identities from the
management API
> OIDC Conformance, RS256 Support, SSO redirect to HLP

- src/Controller/AuthController.php
- src/Form/BasicAdvancedForm.php
Advanced Settings:
Users can be matched by email (default) or user name.
Drupal Roles can be mapped to a claim by value. Drupal Roles can be removed from the user if the claim no longer has the role.
CSS for Fallback Login can added.
Drupal profile fields can be mapped to claims.
> Drupal8 enhancements

- README.txt
- auth0.install
- auth0.module
- auth0.routing.yml
- src/Controller/AuthController.php
- src/Event/Auth0UserSigninEvent.php
- src/Exception/RefreshTokenFailedException.php
- src/Form/BasicAdvancedForm.php
- src/Util/AuthHelper.php
- templates/auth0-login.html.twig
Fixed a couple of bugs and added refresh token support, this has already been pushed to 8.x-2.x-dev in the drupal module.
> Mostekcm add refresh token support

- src/Exception/EmailNotSetException.php
- src/Exception/EmailNotVerifiedException.php
- src/Exception/RefreshTokenFailedException.php
> PHPCS for Exceptions

- src/Event/Auth0UserSignupEvent.php
> PHPCS for Auth0UserSignupEvent.php

- src/Event/Auth0UserSigninEvent.php
@joshcanhelp adjusted for PHPCS.
> Updated Auth0UserSigninEvent for Drupal Coding Standards

- src/Form/BasicSettingsForm.php
> PHPCS BasicSettingsForm.php && default value config updates

- src/Form/BasicAdvancedForm.php
> PHPCS for BasicAdvancedForm.php

- auth0.routing.yml
- src/Controller/AuthController.php
@joshcanhelp There are a fair few changes in this to bring it up to code standards. The next part of this would be to make sure it meets Drupal best practices so removing the static methods of Drupal::logger and Drupal::service and utilise dependency injection which i'll do in a subsequent PR.
> Update PHPCS in AuthController

- auth0.module
- js/auth0.lock.js
- src/Controller/AuthController.php
- templates/auth0-login.html.twig
Fixing a few issues found during testing. See comments in code for details.
> Fix SSO; fix JS errors on login page; fix method name error

- auth0.module
Small change to add support for multivalue fields
> Add support for multivalue fields

- auth0.module
Not sure if this is the intended design but it would be nice to remove roles as well.
> Add support for removing roles as well

- src/Controller/AuthController.php
De-Duped EmailNotVerifiedException in AuthController::processUserLogin by wrapping the if else block inside try and catching the exception outside.
Closes #95 
Existing tests should complete without errors.
> De-Duped EmailNotVerifiedException in AuthController::processUserLogin

- src/Controller/AuthController.php
> Fix inline JavaScript causing resend link not to work

- .circleci/config.yml
Added a CI build to run dependencies and licenses tests using snyk.io
```bash
$ vendor/bin/phpcs modules/auth0/src --standard=Drupal
```
> Add CircleCI build to run Snyk test

- CHANGELOG.md
See CHANGELOG below for changes
> Release 8.x-2.2

- src/Controller/AuthController.php
Properly process HTML message for error output. Stop using JS for the form submit. 
Fixes #145
> Fix verify email form output and remove JS

- src/Controller/AuthController.php
See https://github.com/auth0/auth0-drupal/issues/139.
> Make sessions persist to fix invalid state

- CHANGELOG.md
- auth0.module
Release 8.x-2.3. See changelog below or [milestone](https://github.com/auth0/auth0-drupal/milestone/3?closed=1) for more information.
> Release 8.x-2.3
