auth0/auth0-drupal

auth0.module

The current code allows new user registrations even if the core setting prohibits it. This was enough to cause a 'less critical' SA for another 3rd party auth module recently (https://www.drupal.org/node/2511410) so it should probably be fixed here too.

No registration setting

---

auth0.module

These modifications allow another module to re-enable Drupal registrations without increasing the complexity of the Auth0 base module. Here is a proof of concept reference of how you would enable override this behavior:
<?php
function auth0_override_form_auth0_advanced_form_alter(&$form, $form_state) {
$form['auth0_allow_signup'] = array(
'#type' => 'radios',
'#title' => t('Allow new users to sign up'),
'#default_value' => variable_get('auth0_allow_signup', ''),
'#options' => array(
'' => t('No new user registrations'),
'auth0' => t('New user registrations in Auth0'),
'drupal' => t('New user registrations in Drupal')
),
'' => array(
'#description' => t('Remove the registration form altogether. New users may still be created automatically for social or enterprise logins if the <a …

Drupal registrations

---

auth0.module

JWT::decode requires a list of valid encodings which was not being sent

Fix email verification send

---

auth0.info
auth0.module

I removed the 'require verified email' setting and replaced it with a 'require e-mail address' setting because that more accurately reflects what the current module is checking for. I also added logic to allow unverified email addresses if Drupal core allows that. Verified email addresses are still required for existing accounts to prevent account hijacking.

Non verified email

---

auth0.module

I am working on an implementation where the Auth0 social sign in process will be presented as an option alongside the normal Drupal login form. So I'd like to enable the Auth0 functionality but not replace the entire login, registration, and password reset forms.
This PR adds an Auth0 module setting that allows disabling the replacement of login, registration, and password reset forms. (To be consistent with current behavior, the default is to enable replacement.)
This relates to #17, but this is intended as a more permanent approach.

Allow disabling the replacement of login, registration, password reset forms

---

auth0.module

This PR defines a block with the Auth0 Lock sign in widget in case you want to display this separately from the Drupal login form.
This is especially useful if you have disabled automatic replacement of the Drupal login form via #20.

Add block with the Auth0 Lock sign in widget

---

auth0.module

This fixes a PHP notice ('try to get property of non-object in drupal_unpack()') when attempting to load Drupal user that is not linked with an Auth0 account.
The error can be reproduced by viewing the Auth0 tab for a user account that has not been linked with an Auth0 account.

Fixes PHP notice for unlinked accounts

---

auth0.module

Adds a drupal_alter call to allow other modules to modify lock parameters before using them to generate the fallback link and the widget.

Add a drupal_alter call to auth0 lock configuration

---

auth0.module

On sites that are not mixed mode, and only accept HTTPS, the module fails to appear correctly.

Change CDN call for lock-7.min.js to https 

---

auth0.module

See Issue #28 
This adds an advanced setting to allow for the returnTo URL to have a client_id param appended if the setting is true.
It is false by default, so the current behavior will not change.

Allow for logout url returnTo to be App or Account level

---

src/Controller/AuthController.php

Problem: this controller is catching a class that doesn't exist: `Drupal\auth0\Controller\Exception`
Solution: namespace the `Exception` class to the global namespace, i.e. catch PHP exceptions.

Namespace Exceptions being caught to global

---

.codeclimate.yml
.phpmd.xml

Addresses #46.
Code Climate will do two things:
1. Automatically poll every hour for changes to the repository and update the GPA of the repository. The GPA can be used to gauge how well it is adhering to code style.
1. After adding the Code Climate service ([see howto](https://github.com/auth0/auth0-drupal/settings/installations)) you can get info per-pull request how well the PR itself is adhering to code style.
Here are two relevant docs:
* http://blog.codeclimate.com/blog/2013/11/06/code-climate-for-pull-requests/
* https://github.com/integrations/code-climate
Over time you can see how the code base improves in adhering to the Drupal code style.

Add Drupal 8 module Code Climate config

---

src/Event/Auth0UserSigninEvent.php
src/Event/Auth0UserSignupEvent.php

The $auth0Profile property wasn't assigned correctly in the event.
This PR resolves that by assigning it in the constructor.

Assign properties correctly in events

---

README.md
auth0.module

Added a new advanced setting to make the automatic linking of new Auth0 users to drupal users using email optional (because sometimes multiple drupal users share the same email address).
Also fixed a bug if the additional parameters didn't set the authParams.state value.
And updated the README so that this branch reflects that it is the Drupal7 module.

Drupal 7 Module Enhancement email linking optional and bug fix

---

src/Event/Auth0UserSigninEvent.php
src/Event/Auth0UserSignupEvent.php

Fixes a small bug where event subscribers are unable to retrieve auth0 profile data on sign-in or sign-up.

Allow signin/signup event subscribers to retrieve Auth0 profile data

---

auth0.install

The following module is missing from the file system: auth0_user_services

Fixed the warning appearing while installing the module.

---

src/Form/BasicAdvancedForm.php

Login was failing because of blank `username_claim` and throwing an error
```
Drupal\Core\Database\InvalidQueryException: Query condition 'users_field_data.name IN ()' cannot be empty. in Drupal\Core\Database\Query\Condition->condition() (line 103 of /drupal/web/core/lib/Drupal/Core/Database/Query/Condition.php).
```
This was because `$config->get('auth0_username_claim', 'nickname')` does not return default value like varibale_get() of Drupal 7.

Fixed the missing username claim config.

---

auth0.module
src/Controller/AuthController.php
src/Form/BasicAdvancedForm.php
src/Form/BasicSettingsForm.php
src/Util/AuthHelper.php
templates/auth0-login.html.twig

* adjusted for $userinfo arrays that do not have a provided nickname
* replaced `identities` check with provider check on `user_id`
* added `email_verified` to ID token scope
* changed default signing algorithm to RS256 for new installs
* docblocks
Waiting on #87

Fixed login for new tenants

---

.github/PULL_REQUEST_TEMPLATE.md
auth0.module
src/Util/AuthHelper.php

This PR extends the Auth0 PHP SDK telemetry to report correctly for Drupal applications.

Send correct telemetry for Drupal

---

.gitignore
composer.lock

This PR explicitly adds the `composer.lock` file required for Snyk to report vulnerabilities. 
Ideally this should run as part of a CI build but I found no builds for this repo. Are there any tests on this repo?
https://snyk.io/docs/snyk-for-php/
You can run the check locally using the Snyk CLI.
```sh
snyk test
```
```bash
$ vendor/bin/phpcs modules/auth0/src --standard=Drupal
```

Add composer.lock file

---

src/Controller/AuthController.php

- Fix `returnTo` URL parameter on login URL not redirecting after successful callback processing
- Remove `prompt=none` when redirecting for SSO
- Fix Auth0 logout URL not using Application-level redirects
Closes #136 
1) Go to the Drupal login link with a `returnTo` URL parameter set to a site URL.
2) Log in successfully.
3) Final page should be what `returnTo` was set to.

Fix redirectTo URL parameter

---

src/Controller/AuthController.php

Changes in roles where not detected when the roles are removed on the auth0 management page. This is because array_diff($new_user_roles, $user_roles) only detects added roles.
Changed class AuthController.php 
Changed method auth0UpdateRoles
Remove a role (that is also mapped in Drupal) from an existing Drupal user. Verify that the role is updated after a new login.
No unit tests are available

Fix: changes in roles are now detected correctly

---

src/Controller/AuthController.php

This change removes the "resend email verification" button, as it relates to
a deprecated API endpoint.
Raised through internal discussion and service desk ticket.
```bash
$ vendor/bin/phpcs modules/auth0/src --standard=Drupal
```

Remove resend verfication email button

---

CHANGELOG.md
auth0.module

**Changed**
- Remove resend verfication email button from the email verification template [\#160](https://github.com/auth0/auth0-drupal/pull/160) ([stevehobbsdev](https://github.com/stevehobbsdev))

Release v8.x-2.4
